version: '3'

services:
  webserver-1:
    container_name: webserver-1
    hostname: webserver-1
    build:
      context: ../
      dockerfile: Docker/Dockerfile
    networks:
      internal_network:
        ipv4_address: 172.28.0.2

  webserver-2:
    container_name: webserver-2
    hostname: webserver-2
    build:
      context: ../
      dockerfile: Docker/Dockerfile
    networks:
      internal_network:
        ipv4_address: 172.28.0.3

  proxy:
    container_name: proxy
    hostname: proxy
    image: nginx:alpine
    ports:
      - "443:8443" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./cert:/etc/nginx/certs 
    depends_on:
      - webserver-1
      - webserver-2
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

