---
- name: Deploy Web Server
  hosts: localhost
  become: yes
  tasks:
    - name: Install necessary packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - python3
          - python3-magic
          - php-cgi
          - net-tools
          - python3-pip

    - name: Install Python packages with pip
      pip:
        name: selenium
        state: present

    - name: Copy web server files
      copy:
        src: ./
        dest: /home/ubuntu/final_code
        mode: 0755

    - name: Create systemd service file for the web server
      blockinfile:
        path: /etc/systemd/system/mywebserver.service
        create: yes
        block: |
          [Unit]
          Description=My Web Server
          After=network.target

          [Service]
          Type=simple
          User=root
          WorkingDirectory=/home/ubuntu/final_code
          ExecStart=/usr/bin/python3 server.py localhost 443 demo.crt demo.key
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start web server service
      systemd:
        name: mywebserver
        enabled: yes
        state: started

